name: Github actions
run-name: This is testing out github actions
on: [push]
jobs:
  install_composer:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.1"
        version: 1
    
